# Generated by Django 6.0.7 on 2026-09-01 09:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=300, verbose_name='알림 메시지')),
                ('type', models.CharField(choices=[('info', '정보'), ('success', '성공'), ('warning', '경고'), ('error', '오류')], default='info', max_length=10, verbose_name='알림 종류')),
                ('link', models.CharField(blank=True, max_length=300, null=True, verbose_name='이동 링크')),
                ('read', models.BooleanField(default=False, verbose_name='읽음 여부')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성 일시')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL, verbose_name='수신자')),
            ],
            options={
                'verbose_name': '알림',
                'verbose_name_plural': '알림 목록',
                'db_table': 'notification',
                'ordering': ['-created_at'],
            },
        ),
    ]
