"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.0.8.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""
import os
import environ
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# --- env 설정 추가 ---
env = environ.Env(
    DEBUG=(bool, False)
)
environ.Env.read_env(os.path.join(BASE_DIR, '.env'))
# ----------------------

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = env('SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = env('DEBUG', default=True)

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django_extensions',
    
    # Third Party 패키지
    'rest_framework',
    'corsheaders',
    'drf_spectacular',

    # Local Apps (직접 만든 앱들)
    'common',
    'users',
    'meetings',
    'tasks',
    'projects',
    'requirements',
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

# .env에 MYSQL_HOST가 채워져 있으면(팀 공용 RDS 접속 정보를 아는 사람) MySQL을 쓰고,
# 없으면(.env.example 그대로 두거나 MYSQL_* 항목을 아예 안 채운 팀원) SQLite로 자동 전환된다.
# MySQL을 하드 요구하면 RDS 접속 정보가 없는 팀원은 서버 자체가 안 켜지므로 이 폴백이 필요하다.
if env.str('MYSQL_HOST', default=''):
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.mysql',
            'NAME': env.str('MYSQL_DB'),
            'USER': env.str('MYSQL_USER'),
            'PASSWORD': env.str('MYSQL_PASSWORD'),
            'HOST': env.str('MYSQL_HOST'),
            'PORT': env.int('MYSQL_PORT', default=3306),
        }
    }
else:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }

# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'ko-kr'

TIME_ZONE = 'Asia/Seoul'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'

AUTH_USER_MODEL = 'users.User'

REST_FRAMEWORK = {
# 1. API 문서화 설정 (drf-spectacular)
'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema',

# 2. 사용자 인증 설정 (Simple JWT)
# 2026-08-31: 토큰을 localStorage 대신 HttpOnly 쿠키로 옮기면서, Authorization 헤더가
# 아니라 쿠키에서 JWT를 읽는 커스텀 인증 클래스로 교체(users/authentication.py 참고).
'DEFAULT_AUTHENTICATION_CLASSES': (
    'users.authentication.CookieJWTAuthentication',
),

# (선택) 기본 접근 권한 설정 (예: 인증된 사용자만 접근 가능)
'DEFAULT_PERMISSION_CLASSES': (
    'rest_framework.permissions.IsAuthenticated',
),
}

# Swagger UI에 표시될 기본 정보 설정
SPECTACULAR_SETTINGS = {
    'TITLE': '프로젝트 관리 시스템 API 명세서',
    'DESCRIPTION': '회의록, 기획서, 요구사항 정의, 업무 배정 파이프라인 관리 API',
    'VERSION': '1.0.0',
    'SERVE_INCLUDE_SCHEMA': False,
    # Swagger UI 최적화 설정
    'SWAGGER_UI_SETTINGS': {
        'deepLinking': True,
        'persistAuthorization': True,  # 새로고침해도 인증 토큰 유지
        'displayOperationId': True,
    },
}

# React, Vite 등 프론트엔드 개발 서버 주소 허용
# 개발 모드에서 허용할 프론트엔드 도메인/포트 목록
CORS_ALLOWED_ORIGINS = [
"http://localhost:3000",   # React (Create React App, Next.js 등)
"http://127.0.0.1:3000",
"http://localhost:5173",   # Vite (React / Vue 등)
"http://127.0.0.1:5173",
"http://localhost:8080",   # Vue CLI 등
]

# 인증 정보(Cookie, Authorization 헤더 등)를 포함한 요청 허용
CORS_ALLOW_CREDENTIALS = True

# 2026-08-31: 쿠키 기반 인증으로 옮기면서 CSRF 검증이 다시 필요해졌다(위 CookieJWTAuthentication
# 참고). Django의 CSRF 미들웨어는 Origin/Referer가 다른 포트(localhost:3000 → :8000)로 온
# 요청을 기본적으로 신뢰하지 않으므로, 프론트 개발 서버 주소를 명시적으로 허용해야 한다.
CSRF_TRUSTED_ORIGINS = [
"http://localhost:3000",
"http://127.0.0.1:3000",
]

CORS_ALLOW_HEADERS = [
'accept',
'accept-encoding',
'authorization',
'content-type',
'dnt',
'origin',
'user-agent',
'x-csrftoken',
'x-requested-with',
]

# APPEND_SLASH = False