# Generated by Django 6.0.7 on 2026-08-31 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PipelineHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step_type', models.CharField(choices=[('MEETING_REGISTERED', '회의록 등록'), ('SPEC_GENERATED', '기획서 생성/검토'), ('REQ_DEFINED', '요구사항정의서 확정'), ('TASK_ASSIGNED', '업무 자동 배정'), ('TASK_IN_PROGRESS', '업무 진행 중'), ('COMPLETED', '파이프라인 완료')], max_length=30, verbose_name='파이프라인 단계')),
                ('title', models.CharField(max_length=200, verbose_name='이력 요약 타이틀')),
                ('description', models.TextField(blank=True, null=True, verbose_name='상세 변경 내용/로그')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='발생 일시')),
            ],
            options={
                'verbose_name': '파이프라인 이력',
                'verbose_name_plural': '파이프라인 이력 목록',
                'db_table': 'pipeline_history',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='프로젝트명')),
                ('description', models.TextField(blank=True, null=True, verbose_name='프로젝트 설명')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성 일시')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정 일시')),
            ],
            options={
                'verbose_name': '프로젝트',
                'verbose_name_plural': '프로젝트 목록',
                'db_table': 'project',
            },
        ),
    ]
