# Generated by Django 6.0.7 on 2026-08-26 08:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('meetings', '0001_initial'),
        ('projects', '0001_initial'),
        ('requirements', '0001_initial'),
        ('tasks', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='pipelinehistory',
            name='actor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='작업자/진행자'),
        ),
        migrations.AddField(
            model_name='pipelinehistory',
            name='meeting',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='meetings.meetingnote', verbose_name='관련 회의록'),
        ),
        migrations.AddField(
            model_name='pipelinehistory',
            name='requirement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='requirements.requirementdefinition', verbose_name='관련 요구사항정의서'),
        ),
        migrations.AddField(
            model_name='pipelinehistory',
            name='spec',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='meetings.specdocument', verbose_name='관련 기획서'),
        ),
        migrations.AddField(
            model_name='pipelinehistory',
            name='task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tasks.taskassignment', verbose_name='관련 업무'),
        ),
        migrations.AddField(
            model_name='project',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_projects', to=settings.AUTH_USER_MODEL, verbose_name='프로젝트 관리자'),
        ),
        migrations.AddField(
            model_name='pipelinehistory',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='histories', to='projects.project', verbose_name='프로젝트'),
        ),
    ]
