# Generated by Django 6.0.7 on 2026-09-09 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='period_end',
            field=models.DateField(blank=True, null=True, verbose_name='프로젝트 종료일'),
        ),
        migrations.AddField(
            model_name='project',
            name='period_start',
            field=models.DateField(blank=True, null=True, verbose_name='프로젝트 시작일'),
        ),
    ]
