# Generated by Django 6.0.7 on 2026-09-09 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_project_period_end_project_period_start'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pipelinehistory',
            name='step_type',
            field=models.CharField(choices=[('MEETING_REGISTERED', '회의록 등록'), ('SPEC_AI_GENERATED', '기획서 AI 생성'), ('SPEC_GENERATED', '기획서 생성/검토'), ('REQ_AI_GENERATED', '요구사항정의서 AI 생성'), ('REQ_DEFINED', '요구사항정의서 확정'), ('TASK_AI_SUGGESTED', '업무 배분 AI 추천'), ('TASK_ASSIGNED', '업무 자동 배정'), ('TASK_IN_PROGRESS', '업무 진행 중'), ('COMPLETED', '파이프라인 완료')], max_length=30, verbose_name='파이프라인 단계'),
        ),
    ]
