# Generated by Django 6.0.7 on 2026-08-31 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MeetingNote',
            fields=[
                ('meeting_id', models.AutoField(primary_key=True, serialize=False, verbose_name='회의록 ID')),
                ('title', models.CharField(max_length=200, verbose_name='회의 제목')),
                ('content', models.TextField(verbose_name='회의록 원문/내용')),
                ('summary_content', models.TextField(blank=True, null=True, verbose_name='AI 핵심 요약')),
                ('meeting_date', models.DateTimeField(blank=True, null=True, verbose_name='회의 일시')),
                ('attendees', models.TextField(blank=True, null=True, verbose_name='참석자 목록')),
                ('status', models.CharField(choices=[('DRAFT', '작성 중'), ('PROCESSING', 'AI 분석 중'), ('REVIEWED', '검토 완료')], default='DRAFT', max_length=20, verbose_name='상태')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성 일시')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정 일시')),
            ],
            options={
                'verbose_name': '회의록',
                'verbose_name_plural': '회의록 목록',
                'db_table': 'meeting_note',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SpecDocument',
            fields=[
                ('spec_id', models.AutoField(primary_key=True, serialize=False, verbose_name='기획서 ID')),
                ('title', models.CharField(max_length=200, verbose_name='기획서 제목')),
                ('overview', models.TextField(blank=True, null=True, verbose_name='프로젝트 개요')),
                ('background', models.TextField(blank=True, null=True, verbose_name='추진 배경')),
                ('target_scope', models.TextField(blank=True, null=True, verbose_name='개발 및 추진 범위')),
                ('key_features', models.TextField(blank=True, null=True, verbose_name='주요 기능 요약')),
                ('review_comment', models.TextField(blank=True, null=True, verbose_name='검토 의견')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성 일시')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정 일시')),
            ],
            options={
                'verbose_name': '기획서',
                'verbose_name_plural': '기획서 목록',
                'db_table': 'spec_document',
                'ordering': ['-created_at'],
            },
        ),
    ]
