# Generated by Django 6.0.7 on 2026-08-26 08:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('common', '0001_initial'),
        ('meetings', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='meetingnote',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meeting_notes', to=settings.AUTH_USER_MODEL, verbose_name='작성자'),
        ),
        migrations.AddField(
            model_name='specdocument',
            name='meeting',
            field=models.ForeignKey(db_column='meeting_id', on_delete=django.db.models.deletion.CASCADE, related_name='spec_documents', to='meetings.meetingnote', verbose_name='관련 회의록'),
        ),
        migrations.AddField(
            model_name='specdocument',
            name='reviewer',
            field=models.ForeignKey(blank=True, db_column='reviewer_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_specs', to=settings.AUTH_USER_MODEL, verbose_name='검토자'),
        ),
        migrations.AddField(
            model_name='specdocument',
            name='status_code',
            field=models.ForeignKey(blank=True, db_column='status_code', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='spec_status', to='common.commoncode', verbose_name='검토 상태'),
        ),
    ]
