# Generated by Django 6.0.7 on 2026-08-31 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='specdocument',
            name='final_decisions',
            field=models.TextField(blank=True, null=True, verbose_name='7. 최종 결정사항'),
        ),
        migrations.AddField(
            model_name='specdocument',
            name='problem_definition',
            field=models.TextField(blank=True, null=True, verbose_name='2. 문제 정의'),
        ),
        migrations.AddField(
            model_name='specdocument',
            name='target_users',
            field=models.TextField(blank=True, null=True, verbose_name='3. 대상 사용자'),
        ),
        migrations.AddField(
            model_name='specdocument',
            name='tech_stack',
            field=models.TextField(blank=True, null=True, verbose_name='6. 기술 스택 및 제약사항'),
        ),
        migrations.AddField(
            model_name='specdocument',
            name='user_scenarios',
            field=models.TextField(blank=True, null=True, verbose_name='5. 사용자 시나리오'),
        ),
        migrations.AlterField(
            model_name='specdocument',
            name='background',
            field=models.TextField(blank=True, null=True, verbose_name='추진 배경 (구 필드, 미사용)'),
        ),
        migrations.AlterField(
            model_name='specdocument',
            name='key_features',
            field=models.TextField(blank=True, null=True, verbose_name='4. 주요 기능'),
        ),
        migrations.AlterField(
            model_name='specdocument',
            name='overview',
            field=models.TextField(blank=True, null=True, verbose_name='1. 프로젝트 개요'),
        ),
        migrations.AlterField(
            model_name='specdocument',
            name='target_scope',
            field=models.TextField(blank=True, null=True, verbose_name='개발 및 추진 범위 (구 필드, 미사용)'),
        ),
    ]
