# Generated by Django 6.0.7 on 2026-08-31 09:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0003_specdocument_final_decisions_and_more'),
        ('projects', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='meetingnote',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='meeting_notes', to='projects.project', verbose_name='소속 프로젝트'),
        ),
    ]
