# Generated by Django 6.0.7 on 2026-09-01 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0005_seed_proposal_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='specdocument',
            name='period_end',
            field=models.DateField(blank=True, null=True, verbose_name='프로젝트 종료일'),
        ),
        migrations.AddField(
            model_name='specdocument',
            name='period_start',
            field=models.DateField(blank=True, null=True, verbose_name='프로젝트 시작일'),
        ),
    ]
