# Generated by Django 6.0.7 on 2026-09-07 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0006_specdocument_period_end_specdocument_period_start'),
    ]

    operations = [
        migrations.AddField(
            model_name='specdocument',
            name='evidence_data',
            field=models.TextField(blank=True, null=True, verbose_name='섹션별 근거 데이터'),
        ),
    ]
