# Generated by Django 6.0.7 on 2026-09-10 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0007_specdocument_evidence_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specdocument',
            name='key_features',
            field=models.TextField(blank=True, null=True, verbose_name='5. 주요 기능'),
        ),
        migrations.AlterField(
            model_name='specdocument',
            name='target_users',
            field=models.TextField(blank=True, null=True, verbose_name='4. 대상 사용자'),
        ),
        migrations.AlterField(
            model_name='specdocument',
            name='user_scenarios',
            field=models.TextField(blank=True, null=True, verbose_name='3. 프로젝트 목표'),
        ),
    ]
