# Generated by Django 6.0.7 on 2026-09-10 10:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0008_alter_specdocument_key_features_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='specdocument',
            old_name='user_scenarios',
            new_name='goals',
        ),
    ]
