# Generated by Django 6.0.7 on 2026-09-15 03:08

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0009_specdocument_goal_section_labels'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MeetingAnalysisJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('PENDING', '대기'), ('RUNNING', '진행 중'), ('SUCCESS', '완료'), ('ERROR', '실패')], default='PENDING', max_length=10, verbose_name='상태')),
                ('stage', models.CharField(blank=True, default='', max_length=100, verbose_name='현재 진행 단계(사람이 읽는 라벨)')),
                ('result', models.JSONField(blank=True, null=True, verbose_name='성공 시 결과(MeetingNoteAnalyzeView 응답과 동일)')),
                ('error_message', models.TextField(blank=True, null=True, verbose_name='실패 시 오류 메시지')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='meeting_analysis_jobs', to=settings.AUTH_USER_MODEL, verbose_name='실행자')),
                ('note', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analysis_jobs', to='meetings.meetingnote', verbose_name='대상 회의록')),
            ],
            options={
                'verbose_name': '기획서 생성 실행 작업',
                'verbose_name_plural': '기획서 생성 실행 작업 목록',
                'db_table': 'meeting_analysis_job',
                'ordering': ['-created_at'],
            },
        ),
    ]
