# Generated by Django 6.0.7 on 2026-09-18 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0011_spec_validation'),
    ]

    operations = [
        migrations.AddField(
            model_name='specdocument',
            name='evidence_items',
            field=models.TextField(blank=True, null=True, verbose_name='항목 단위 근거 데이터 (원문 보기용)'),
        ),
    ]
