# Generated by Django 6.0.7 on 2026-09-22 03:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0012_specdocument_evidence_items'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SpecValidationReport',
        ),
    ]
