# Generated by Django 6.0.7 on 2026-08-25 06:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('meetings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpecDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('summary', models.TextField(blank=True)),
                ('file', models.FileField(blank=True, null=True, upload_to='specs/%Y/%m/')),
                ('status', models.CharField(choices=[('GENERATING', '생성 중'), ('COMPLETED', '생성 완료'), ('REVIEWED', '검토 완료')], default='GENERATING', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('meeting', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='spec', to='meetings.meetingnote')),
            ],
        ),
    ]
