# Generated by Django 6.0.7 on 2026-08-31 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TaskAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_title', models.CharField(max_length=200, verbose_name='업무 제목')),
                ('task_description', models.TextField(verbose_name='업무 상세 내용')),
                ('status', models.CharField(choices=[('PENDING_APPROVAL', '승인 대기'), ('APPROVED', '승인 및 알림 완료'), ('IN_PROGRESS', '진행 중'), ('COMPLETED', '완료')], default='PENDING_APPROVAL', max_length=20, verbose_name='진행/승인 상태')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='시작 예정일')),
                ('due_date', models.DateField(blank=True, null=True, verbose_name='마감 예정일')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성 일시')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정 일시')),
            ],
            options={
                'verbose_name': '배정 업무',
                'verbose_name_plural': '배정 업무 목록',
                'db_table': 'task_assignment',
                'ordering': ['-created_at'],
            },
        ),
    ]
