# Generated by Django 6.0.7 on 2026-09-01 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskassignment',
            name='progress',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='진행률(%)'),
        ),
        migrations.AddField(
            model_name='taskassignment',
            name='reject_reason',
            field=models.TextField(blank=True, null=True, verbose_name='반려 사유'),
        ),
        migrations.AlterField(
            model_name='taskassignment',
            name='status',
            field=models.CharField(choices=[('PENDING_APPROVAL', '승인 대기'), ('APPROVED', '승인 및 알림 완료'), ('REJECTED', '반려'), ('IN_PROGRESS', '진행 중'), ('COMPLETED', '완료')], default='PENDING_APPROVAL', max_length=20, verbose_name='진행/승인 상태'),
        ),
    ]
