# Generated by Django 6.0.7 on 2026-09-07 03:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
        ('projects', '0002_initial'),
        ('tasks', '0003_taskassignment_progress_taskassignment_reject_reason_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taskassignment',
            name='due_date',
        ),
        migrations.RemoveField(
            model_name='taskassignment',
            name='status',
        ),
        migrations.RemoveField(
            model_name='taskassignment',
            name='task_description',
        ),
        migrations.RemoveField(
            model_name='taskassignment',
            name='task_title',
        ),
        migrations.AddField(
            model_name='taskassignment',
            name='assigned_workload',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='배정 시점 부하율'),
        ),
        migrations.AddField(
            model_name='taskassignment',
            name='assignment_reason',
            field=models.TextField(blank=True, null=True, verbose_name='배정 근거'),
        ),
        migrations.AddField(
            model_name='taskassignment',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='업무 상세 설명'),
        ),
        migrations.AddField(
            model_name='taskassignment',
            name='difficulty_code',
            field=models.ForeignKey(blank=True, db_column='difficulty_code', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='task_difficulty', to='common.commoncode', verbose_name='난이도 코드'),
        ),
        migrations.AddField(
            model_name='taskassignment',
            name='difficulty_reason',
            field=models.TextField(blank=True, null=True, verbose_name='난이도 판단 근거'),
        ),
        migrations.AddField(
            model_name='taskassignment',
            name='end_date',
            field=models.DateField(blank=True, null=True, verbose_name='종료 예정일'),
        ),
        migrations.AddField(
            model_name='taskassignment',
            name='epic_no',
            field=models.CharField(default='', max_length=20, verbose_name='epic ID'),
        ),
        migrations.AddField(
            model_name='taskassignment',
            name='epic_title',
            field=models.CharField(default='', max_length=200, verbose_name='epic 제목'),
        ),
        migrations.AddField(
            model_name='taskassignment',
            name='estimated_hours',
            field=models.FloatField(blank=True, null=True, verbose_name='예상 소요 시간'),
        ),
        migrations.AddField(
            model_name='taskassignment',
            name='git_status_code',
            field=models.ForeignKey(blank=True, db_column='git_status_code', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='task_git_status', to='common.commoncode', verbose_name='Git 연동 상태 코드'),
        ),
        migrations.AddField(
            model_name='taskassignment',
            name='linked_branch',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='연결 브랜치명'),
        ),
        migrations.AddField(
            model_name='taskassignment',
            name='linked_pr_number',
            field=models.IntegerField(blank=True, null=True, verbose_name='연결 PR 번호'),
        ),
        migrations.AddField(
            model_name='taskassignment',
            name='linked_pr_url',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='연결 PR 링크'),
        ),
        migrations.AddField(
            model_name='taskassignment',
            name='parent_task',
            field=models.CharField(blank=True, db_column='parent_task_id', max_length=20, null=True, verbose_name='부모 업무 번호'),
        ),
        migrations.AddField(
            model_name='taskassignment',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='task_assignments', to='projects.project', verbose_name='프로젝트'),
        ),
        migrations.AddField(
            model_name='taskassignment',
            name='status_code',
            field=models.ForeignKey(blank=True, db_column='status_code', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='task_status', to='common.commoncode', verbose_name='업무 상태 코드'),
        ),
        migrations.AddField(
            model_name='taskassignment',
            name='task_no',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='업무배분 번호 (예: TASK-001)'),
        ),
        migrations.AddField(
            model_name='taskassignment',
            name='title',
            field=models.CharField(default='', max_length=200, verbose_name='업무명'),
        ),
        migrations.AlterField(
            model_name='taskassignment',
            name='progress',
            field=models.IntegerField(default=0, verbose_name='진행률(%)'),
        ),
        migrations.AlterField(
            model_name='taskassignment',
            name='reject_reason',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='반려 사유'),
        ),
        migrations.AlterField(
            model_name='taskassignment',
            name='start_date',
            field=models.DateField(blank=True, null=True, verbose_name='시작일'),
        ),
    ]
