# Generated by Django 6.0.7 on 2026-09-14 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0005_taskgenerationjob'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeExperienceTagCache',
            fields=[
                ('text_hash', models.CharField(max_length=64, primary_key=True, serialize=False, verbose_name='경력기술서 원문 SHA-256')),
                ('tags', models.JSONField(default=list, verbose_name='추출된 경험 태그')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '경력기술서 태그 캐시',
                'verbose_name_plural': '경력기술서 태그 캐시 목록',
                'db_table': 'employee_experience_tag_cache',
            },
        ),
    ]
