# Generated by Django 6.0.7 on 2026-09-16 06:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0006_employeeexperiencetagcache'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='taskassignment',
            name='original_assigned_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='AI 최초 추천 담당자(확정 시점, 이후 안 바뀜)'),
        ),
        migrations.AddField(
            model_name='taskassignment',
            name='original_assignment_reason',
            field=models.TextField(blank=True, null=True, verbose_name='AI 최초 배정 근거(확정 시점, 이후 안 바뀜)'),
        ),
    ]
