# Generated by Django 6.1.1 on 2026-09-22 06:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0007_taskassignment_original_assigned_user_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='taskassignment',
            name='is_task_header',
            field=models.BooleanField(default=False, verbose_name='Subtask를 묶는 표시용 Task 행인지(직접 배정 대상 아님)'),
        ),
        migrations.AlterField(
            model_name='taskassignment',
            name='assigned_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to=settings.AUTH_USER_MODEL, verbose_name='담당자'),
        ),
    ]
