# Generated by Django 6.0.7 on 2026-08-31 00:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CommonCodeGroup',
            fields=[
                ('group_code', models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='코드 그룹 ID')),
                ('group_name', models.CharField(max_length=100, verbose_name='코드 그룹명')),
                ('description', models.TextField(blank=True, null=True, verbose_name='설명')),
                ('is_active', models.BooleanField(default=True, verbose_name='사용 여부')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성 일시')),
            ],
            options={
                'verbose_name': '공통 코드 그룹',
                'verbose_name_plural': '공통 코드 그룹 목록',
                'db_table': 'common_code_group',
            },
        ),
        migrations.CreateModel(
            name='CommonCode',
            fields=[
                ('code_id', models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='코드 ID')),
                ('code_name', models.CharField(max_length=100, verbose_name='코드명')),
                ('sort_order', models.IntegerField(default=0, verbose_name='정렬 순서')),
                ('is_active', models.BooleanField(default=True, verbose_name='사용 여부')),
                ('description', models.TextField(blank=True, null=True, verbose_name='설명')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성 일시')),
                ('group', models.ForeignKey(db_column='group_code', on_delete=django.db.models.deletion.CASCADE, related_name='codes', to='common.commoncodegroup', verbose_name='코드 그룹')),
            ],
            options={
                'verbose_name': '공통 코드',
                'verbose_name_plural': '공통 코드 목록',
                'db_table': 'common_code',
                'ordering': ['group', 'sort_order'],
            },
        ),
    ]
