# Generated by Django 6.0.7 on 2026-08-26 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RequirementDefinition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='요구사항 정의서 제목')),
                ('version', models.CharField(default='v1.0', max_length=20, verbose_name='버전')),
                ('description', models.TextField(blank=True, null=True, verbose_name='설명')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성 일시')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정 일시')),
            ],
            options={
                'verbose_name': '요구사항 정의서',
                'verbose_name_plural': '요구사항 정의서 목록',
                'db_table': 'requirement_definition',
            },
        ),
        migrations.CreateModel(
            name='RequirementItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('req_code', models.CharField(max_length=50, verbose_name='요구사항 코드 (예: REQ-01)')),
                ('req_name', models.CharField(max_length=200, verbose_name='요구사항명')),
                ('description', models.TextField(verbose_name='요구사항 상세 내용')),
                ('difficulty', models.CharField(blank=True, max_length=20, null=True, verbose_name='난이도 (상/중/하)')),
                ('category', models.CharField(blank=True, max_length=50, null=True, verbose_name='기능 카테고리')),
            ],
            options={
                'verbose_name': '요구사항 상세 항목',
                'verbose_name_plural': '요구사항 상세 항목 목록',
                'db_table': 'requirement_item',
            },
        ),
    ]
