# Generated by Django 6.0.7 on 2026-08-31 00:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('common', '0001_initial'),
        ('meetings', '0002_initial'),
        ('requirements', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='requirementdefinition',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_requirements', to=settings.AUTH_USER_MODEL, verbose_name='작성자'),
        ),
        migrations.AddField(
            model_name='requirementdefinition',
            name='spec',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requirement_definitions', to='meetings.specdocument', verbose_name='관련 기획서'),
        ),
        migrations.AddField(
            model_name='requirementitem',
            name='priority_code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='req_priority', to='common.commoncode', verbose_name='우선순위'),
        ),
        migrations.AddField(
            model_name='requirementitem',
            name='req_def',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='requirements.requirementdefinition', verbose_name='요구사항 정의서'),
        ),
    ]
