# Generated by Django 6.0.7 on 2026-09-07 01:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_initial'),
        ('requirements', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='requirementdefinition',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requirement_definitions', to='projects.project', verbose_name='소속 프로젝트'),
        ),
        migrations.AddField(
            model_name='requirementitem',
            name='category_2',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='기능 카테고리 2'),
        ),
    ]
