# Generated by Django 6.0.7 on 2026-09-07 08:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
        ('requirements', '0003_requirementdefinition_project_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='requirementdefinition',
            name='status_code',
            field=models.ForeignKey(blank=True, limit_choices_to={'group_code': 'REQSPEC_STATUS'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='req_definition_status', to='common.commoncode', verbose_name='승인 상태'),
        ),
    ]
