# Generated by Django 6.0.7 on 2026-09-08 05:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
        ('requirements', '0004_requirementdefinition_status_code'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='requirementitem',
            options={'ordering': ['order', 'id'], 'verbose_name': '요구사항 상세 항목', 'verbose_name_plural': '요구사항 상세 항목 목록'},
        ),
        migrations.AddField(
            model_name='requirementitem',
            name='order',
            field=models.FloatField(default=0, verbose_name='표시 순서'),
        ),
        migrations.AlterField(
            model_name='requirementdefinition',
            name='status_code',
            field=models.ForeignKey(blank=True, limit_choices_to={'group_id': 'REQSPEC_STATUS'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='req_definition_status', to='common.commoncode', verbose_name='승인 상태'),
        ),
    ]
