# Generated by Django 6.0.7 on 2026-09-08 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requirements', '0005_alter_requirementitem_options_requirementitem_order_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='requirementdefinition',
            name='reject_reason',
            field=models.TextField(blank=True, null=True, verbose_name='반려 사유'),
        ),
    ]
