# Generated by Django 6.0.7 on 2026-09-22 03:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('requirements', '0009_requirement_validation'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RequirementValidationReport',
        ),
    ]
