# Generated by Django 6.0.7 on 2026-08-31 00:39

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('emp_no', models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='사원번호')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='전화번호')),
                ('is_busy', models.BooleanField(default=False, help_text='현재 업무가 진행 중인지 여부', verbose_name='현재 작업 중 여부')),
                ('dept_code', models.ForeignKey(blank=True, db_column='dept_code', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_dept', to='common.commoncode', verbose_name='부서 코드')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('job_role_code', models.ForeignKey(blank=True, db_column='job_role_code', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_job_role', to='common.commoncode', verbose_name='직무 코드')),
                ('position_code', models.ForeignKey(blank=True, db_column='position_code', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_position', to='common.commoncode', verbose_name='직급 코드')),
                ('role_code', models.ForeignKey(blank=True, db_column='role_code', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_role', to='common.commoncode', verbose_name='권한 코드')),
                ('status_code', models.ForeignKey(blank=True, db_column='status_code', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_status', to='common.commoncode', verbose_name='상태 코드')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': '사용자',
                'verbose_name_plural': '사용자 목록',
                'db_table': 'user',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='UserCertification',
            fields=[
                ('cert_id', models.AutoField(primary_key=True, serialize=False, verbose_name='자격증 ID')),
                ('acquired_date', models.DateField(blank=True, null=True, verbose_name='취득일')),
                ('cert_code', models.ForeignKey(db_column='cert_code', on_delete=django.db.models.deletion.CASCADE, to='common.commoncode', verbose_name='자격증 코드')),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, related_name='certifications', to=settings.AUTH_USER_MODEL, verbose_name='사용자')),
            ],
            options={
                'verbose_name': '사용자 자격증',
                'verbose_name_plural': '사용자 자격증 목록',
                'db_table': 'user_certification',
            },
        ),
        migrations.CreateModel(
            name='UserSkill',
            fields=[
                ('skill_id', models.AutoField(primary_key=True, serialize=False, verbose_name='기술 ID')),
                ('proficiency_level', models.IntegerField(default=1, verbose_name='숙련도 (1~5)')),
                ('skill_code', models.ForeignKey(db_column='skill_code', on_delete=django.db.models.deletion.CASCADE, to='common.commoncode', verbose_name='기술 코드')),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, related_name='skills', to=settings.AUTH_USER_MODEL, verbose_name='사용자')),
            ],
            options={
                'verbose_name': '사용자 기술',
                'verbose_name_plural': '사용자 기술 목록',
                'db_table': 'user_skill',
            },
        ),
    ]
