# Generated by Django 6.0.7 on 2026-08-31 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='hire_date',
            field=models.DateField(blank=True, null=True, verbose_name='입사일'),
        ),
        migrations.AddField(
            model_name='user',
            name='past_projects',
            field=models.TextField(blank=True, null=True, verbose_name='참여 프로젝트 이력(콤마 구분)'),
        ),
        migrations.AddField(
            model_name='user',
            name='resign_date',
            field=models.DateField(blank=True, null=True, verbose_name='퇴사일'),
        ),
    ]
