# Generated by Django 6.0.7 on 2026-09-07 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_hire_date_user_past_projects_user_resign_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='session_key',
            field=models.CharField(blank=True, editable=False, max_length=32, null=True, verbose_name='현재 활성 세션 키'),
        ),
    ]
