# Generated by Django 6.0.7 on 2026-09-07 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_session_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='session_last_seen',
            field=models.DateTimeField(blank=True, editable=False, null=True, verbose_name='활성 세션 마지막 활동 시각'),
        ),
    ]
