# Generated by Django 6.0.7 on 2026-09-08 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_session_last_seen'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_onboarded',
            field=models.BooleanField(default=False, help_text='최초 프로필 설정/온보딩 완료 여부', verbose_name='온보딩 완료 여부'),
        ),
    ]
